modLoader="javafml"
loaderVersion="[47,)"  # Для Forge 1.20.1
license="MIT"
[[mods]]
modId="voicedebuffmod"
version="${file.jarVersion}"
displayName="Voice Debuff Mod"
description="off voice"
authors="ifrit"
