modLoader="javafml"
loaderVersion="[47,)"  # Для Forge 1.20.1
license="MIT"
[[mods]]
modId="voicedebuffmod"
version="1.0"
displayName="Voice Debuff Mod"
authors="YourName"
description="Mutes players when they have debuffs"
